apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
      - name: landing-container
        image: guddytech/landing-page-server
        ports:
        - containerPort: 80
        
        