name: Check Main Branch Protection

on:
  push:
    branches:
      - main

jobs:
  check-main-branch-protection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.1
      
      - name: Get branch protection status
        id: get_branch_protection
        run: |
          branch_protection=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/guddytech/food-app-k8s-docker-sys-archi/branches/main/protection)
          echo "Branch Protection API response: $branch_protection"
          error_message=$(echo $branch_protection | jq -r '.message')
          if [ "$error_message" = "Branch not protected" ]; then
            echo "protection_enabled=false" >> $GITHUB_ENV
          else
            echo "protection_enabled=true" >> $GITHUB_ENV
          fi
      
      - name: Fail if main branch protection not found
        if: env.protection_enabled == 'false'
        run: |
          echo "Main branch is not protected!"
          exit 1
