name: Check Main Branch Protection

on:
  push:
    branches:
      - main

jobs:
  check-main-branch-protection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run script to check main branch protection
        id: check_main_branch_protection
        run: |
          #!/bin/bash
          
          # Check if main branch is protected
          if ! git branch --remote --show-current | grep -q "Protected branches"; then
            echo "Main branch is not protected!"
            exit 1
          fi
          
          echo "Main branch is protected."
      
      - name: Fail if main branch protection not found
        if: ${{ failure() }}
        run: exit 1
