name: Check Main Branch Protection

on:
  push:
    branches:
      - main

jobs:
  check-main-branch-protection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get branch protection status
        id: get_branch_protection
        run: |
          branch_protection=$(curl -s -H "Authorization: token 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" https://api.github.com/repos/guddytech/food-app-k8s-docker-sys-archi/branches/main/protection)
          echo "::set-output name=protection_enabled::$(echo $branch_protection | jq '.enabled')"
      
      - name: Fail if main branch protection not found
        if: ${{ steps.get_branch_protection.outputs.protection_enabled == 'false' }}
        run: |
          echo "Main branch is not protected!"
          exit 1
