name: Check Main Branch Protection

on:
  push:
    branches:
      - main

jobs:
  check-main-branch-protection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get branch protection status
        id: get_branch_protection
        run: |
          branch_protection=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/branches/main/protection)
          echo "Branch Protection API response: $branch_protection"
          error_message=$(echo $branch_protection | jq -r '.message')
          if [ "$error_message" = "Branch not protected" ]; then
            echo "::set-output name=protection_enabled::false"
          else
            echo "::set-output name=protection_enabled::true"
          fi
      
      - name: Fail if main branch protection not found
        if: ${{ steps.get_branch_protection.outputs.protection_enabled == 'false' }}
        run: |
          echo "Main branch is not protected!"
          exit 1
